In [1]:
import pickle
import math
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# load s2and production model -> Clusterer obj
with open("data/production_model.pickle", "rb") as _pkl_file:
    prod_model = pickle.load(_pkl_file)
    clusterer = prod_model['clusterer']

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

2022-10-16 05:46:40,451 - s2and - WARNING - You haven't set `main_data_dir` in data/path_config.json! Using data/ as default data directory.


In [3]:
from os.path import join
from s2and.data import ANDData

In [16]:
# load the "arnetminer" dataset in inference mode and verify S2AND README instructions

dataset_name = "arnetminer"
parent_dir = f"data/{dataset_name}"
dataset = ANDData(
    signatures=join(parent_dir, f"{dataset_name}_signatures.json"),
    papers=join(parent_dir, f"{dataset_name}_papers.json"),
    mode="inference",
    specter_embeddings=join(parent_dir, f"{dataset_name}_specter.pickle"),
    block_type="s2",
    name=dataset_name,
)
#     clusters=join(parent_dir, f"{dataset_name}_clusters.json"),
#     train_pairs_size=100000,
#     val_pairs_size=10000,
#     test_pairs_size=10000,
#     n_jobs=8,
# )

2022-10-16 00:37:04,635 - s2and - INFO - loading papers
2022-10-16 00:37:06,116 - s2and - INFO - loaded papers
2022-10-16 00:37:06,117 - s2and - INFO - loading signatures
2022-10-16 00:37:06,441 - s2and - INFO - loaded signatures
2022-10-16 00:37:06,442 - s2and - INFO - loading clusters
2022-10-16 00:37:06,442 - s2and - INFO - loaded clusters, loading specter
2022-10-16 00:37:06,684 - s2and - INFO - loaded specter, loading cluster seeds
2022-10-16 00:37:06,685 - s2and - INFO - loaded cluster seeds
2022-10-16 00:37:06,686 - s2and - INFO - loading name counts
2022-10-16 00:37:27,237 - s2and - INFO - loaded name counts
2022-10-16 00:37:27,444 - s2and - INFO - preprocessing papers
Preprocessing papers 2/2: 100%|█████████████████████████████████████████████████████████████████| 53959/53959 [00:16<00:00, 3184.63it/s]
2022-10-16 00:37:53,930 - s2and - INFO - preprocessed papers
2022-10-16 00:37:53,931 - s2and - INFO - preprocessing signatures
Preprocessing signatures: 100%|███████████████████

In [18]:
# Make predictions using the prod model
pred_clusters, pred_distance_matrices = clusterer.predict(dataset.get_blocks(), dataset)

2022-10-16 00:40:55,733 - s2and - INFO - Making 130 distance matrices
2022-10-16 00:40:55,735 - s2and - INFO - Initializing pairwise_probas
2022-10-16 00:40:55,738 - s2and - INFO - Pairwise probas initialized, starting making all pairs
2022-10-16 00:40:55,739 - s2and - INFO - Featurizing batch 0/1
2022-10-16 00:40:55,740 - s2and - INFO - Getting constraints
2022-10-16 00:40:58,365 - s2and - INFO - Loading cache...
2022-10-16 00:40:58,377 - s2and - INFO - Cache initiated.
2022-10-16 00:40:58,454 - s2and - INFO - Creating 530735 pieces of work
Creating work: 530735it [00:00, 811561.29it/s]
2022-10-16 00:40:59,111 - s2and - INFO - Created pieces of work
2022-10-16 00:40:59,112 - s2and - INFO - Cached changed, doing 497000 work in parallel
Doing work: 100%|█████████████████████████████████████████████████████████████████████████████| 497000/497000 [04:50<00:00, 1710.31it/s]
2022-10-16 00:45:52,251 - s2and - INFO - Work completed
2022-10-16 00:45:52,252 - s2and - INFO - Writing to on disk c

From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
From version 0.24, get_params will raise an AttributeError if a parameter cannot b

In [25]:
# Install microsoft/hummingbird
!pip install git+https://github.com/microsoft/hummingbird.git@mainterl/fine-tune-trees

  Cloning https://github.com/microsoft/hummingbird.git (to revision mainterl/fine-tune-trees) to /scratch/cpu008/3679532/pip-req-build-j_e01feo
  Running command git clone --filter=blob:none --quiet https://github.com/microsoft/hummingbird.git /scratch/cpu008/3679532/pip-req-build-j_e01feo
  Running command git checkout -b mainterl/fine-tune-trees --track origin/mainterl/fine-tune-trees
  Switched to a new branch 'mainterl/fine-tune-trees'
  Branch 'mainterl/fine-tune-trees' set up to track remote branch 'mainterl/fine-tune-trees' from 'origin'.
  Resolved https://github.com/microsoft/hummingbird.git to commit 9d16d38f66c35ec18c95a9ce72f0acd9d7080c30
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
  Using cached onnxconverter_common-1.7.0-py2.py3-none-any.whl (64 kB)
  Using cached protobuf-4.21.7-cp37-abi3-manylinux2014_x86_64.whl (408 kB)
  U

In [4]:
import hummingbird.ml
from hummingbird.ml import constants
import torch
import lightgbm as lgb

In [56]:
clusterer.classifier

LGBMClassifier(colsample_bytree=0.9476923894333807,
               learning_rate=0.09140456060593606, max_depth=45, metric='auc',
               min_child_samples=1779, min_child_weight=1.4729203134152992e-06,
               min_split_gain=1.184108047915407,
               monotone_constraints='1,1,1,0,0,0,0,1,1,1,0,1,0,-1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,-1,-1,-1,0,-1,0,0,0,0,0,0',
               monotone_constraints_method='advanced',
               monotone_penalty=1.009268715649836, n_estimators=1796, n_jobs=16,
               num_leaves=55, objective='binary', random_state=42,
               reg_alpha=7.44123492799962e-05,
               reg_lambda=1.8145145831930983e-05, subsample=0.7930734824387159,
               tree_learner='data', verbose=-1)

In [61]:
# Convert the S2 LGBM classifier to torch
def convert_gbdt_to_torch(classifier_model, test_input=None, dropout=0.1):
    humming = hummingbird.ml.convert(classifier_model, "torch", test_input=test_input,
                                     extra_config={constants.FINE_TUNE: True,
                                                   constants.FINE_TUNE_DROPOUT_PROB: dropout})
    return humming.model

hm_model = convert_gbdt_to_torch(clusterer.classifier)

Finished loading model, total used 259 iterations


In [6]:
# Parameter count for the converted model
sum(p.numel() for p in hm_model.parameters() if p.requires_grad)

1357419

In [6]:
# load dataset in "train" mode

from s2and.model import PairwiseModeler
from s2and.featurizer import FeaturizationInfo, featurize
from s2and.eval import pairwise_eval

dataset_name = "arnetminer"
parent_dir = f"data/{dataset_name}"
dataset = ANDData(
    signatures=join(parent_dir, f"{dataset_name}_signatures.json"),
    papers=join(parent_dir, f"{dataset_name}_papers.json"),
    mode="train",
    specter_embeddings=join(parent_dir, f"{dataset_name}_specter.pickle"),
    clusters=join(parent_dir, f"{dataset_name}_clusters.json"),
    block_type="s2",
    train_pairs_size=100000,
    val_pairs_size=10000,
    test_pairs_size=10000,
    name=dataset_name,
    n_jobs=8,
)

featurization_info = FeaturizationInfo()
# the cache will make it faster to train multiple times - it stores the features on disk for you
train, val, test = featurize(dataset, featurization_info, n_jobs=8, use_cache=True)

2022-10-16 05:47:04,455 - s2and - INFO - loading papers
2022-10-16 05:47:05,828 - s2and - INFO - loaded papers
2022-10-16 05:47:05,829 - s2and - INFO - loading signatures
2022-10-16 05:47:05,973 - s2and - INFO - loaded signatures
2022-10-16 05:47:05,976 - s2and - INFO - loading clusters
2022-10-16 05:47:06,148 - s2and - INFO - loaded clusters, loading specter
2022-10-16 05:47:06,489 - s2and - INFO - loaded specter, loading cluster seeds
2022-10-16 05:47:06,490 - s2and - INFO - loaded cluster seeds
2022-10-16 05:47:06,492 - s2and - INFO - making signature to cluster id
2022-10-16 05:47:06,495 - s2and - INFO - made signature to cluster id
2022-10-16 05:47:06,496 - s2and - INFO - loading name counts
2022-10-16 05:47:28,797 - s2and - INFO - loaded name counts
2022-10-16 05:47:29,010 - s2and - INFO - preprocessing papers
Preprocessing papers 2/2: 100%|█████████████████████████████████████████████████████████████████| 53959/53959 [00:23<00:00, 2342.50it/s]
2022-10-16 05:48:05,548 - s2and - I

In [7]:
X_train, y_train, _ = train
X_val, y_val, _ = val
X_test, y_test, _ = test

In [84]:
# Verify S2AND pairwise classifier training instructions

pairwise_model = PairwiseModeler(
    n_iter=25, monotone_constraints=featurization_info.lightgbm_monotone_constraints
)  # calibrate=True, --> threw "unexpected keyword argument error"

pairwise_model.fit(X_train, y_train, X_val, y_val)

100%|████████████████████████████████████████████████████████████████| 25/25 [15:28<00:00, 37.12s/trial, best loss: -0.9573554850856976]


In [53]:
# Converting NANs to -1 to allow torch to process data; check if this makes sense

def get_tensors(X_train, y_train, X_val, y_val, X_test, y_test):
    X_train_tensor = torch.tensor(X_train); X_train_tensor = torch.nan_to_num(X_train_tensor, -1)
    y_train_tensor = torch.tensor(y_train)

    X_val_tensor = torch.tensor(X_val); X_val_tensor = torch.nan_to_num(X_val_tensor, -1)
    y_val_tensor = torch.tensor(y_val)

    X_test_tensor = torch.tensor(X_test); X_test_tensor = torch.nan_to_num(X_test_tensor, -1)
    y_test_tensor = torch.tensor(y_test)
    
    return X_train_tensor, y_train_tensor, X_val_tensor, y_val_tensor, X_test_tensor, y_test_tensor

X_train_tensor, y_train_tensor, \
X_val_tensor, y_val_tensor, \
X_test_tensor, y_test_tensor = get_tensors(X_train, y_train, X_val, y_val, X_test, y_test)

In [21]:
# Check the converted model's output
hm_model.eval()
rand_indices = torch.randint(0, len(X_train_tensor), (10,))
print(rand_indices)
with torch.no_grad():
    pred = hm_model(X_train_tensor[rand_indices])
print(y_train_tensor[rand_indices])
print(pred[0])

tensor([30908, 77783, 96986, 69385, 94517, 45145, 10119, 56252, 82921, 56919])
tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 1.], dtype=torch.float64)
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])


In [11]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)
print(f"Using device={device}")

Using device=cuda


In [62]:
# Try and release memory

hm_model = None
X_train_tensor = None
y_train_tensor = None
X_val_tensor = None
y_val_tensor = None
X_test_tensor = None
y_test_tensor = None
torch.cuda.empty_cache()

In [63]:
# Get tensors

X_train_tensor, y_train_tensor, \
X_val_tensor, y_val_tensor, \
X_test_tensor, y_test_tensor = get_tensors(X_train, y_train, X_val, y_val, X_test, y_test)

In [68]:
# Fine tune torch model
hm_model = convert_gbdt_to_torch(clusterer.classifier, test_input=X_train_tensor.numpy())
hm_model.to(device)

y_train_tensor = y_train_tensor.float()  # Converting to keep output and prediction dtypes consistent

loss_fn = torch.nn.BCELoss()
loss = None

def predict_proba(model, input):
    return model(input)[1][:, 1]
def evaluate(model, input, output):
    return (sum(model(input)[0] == output) / len(input)).item()

optimizer = torch.optim.AdamW(hm_model.parameters(), lr=1e-3, weight_decay=5e-4)
print("\nStarting fine-tuning:\n")
with torch.no_grad():
    hm_model.eval()
    print("Initial dev accuracy:", evaluate(hm_model, X_val_tensor.to(device), y_val_tensor.to(device))*100, "%")
hm_model.train()

batch_size = 20000
for i in range(20):  # epoch
    for j in range(0, len(X_train_tensor), batch_size):  # batch
        X_batch = X_train_tensor[j:j+batch_size].to(device)
        y_batch = y_train_tensor[j:j+batch_size].to(device)
        
        optimizer.zero_grad()
        y_ = predict_proba(hm_model, X_batch)
        assert y_.requires_grad
        
        loss = loss_fn(y_, y_batch)
        loss.backward()
        optimizer.step()
        
        # Print batch loss
        with torch.no_grad():
            hm_model.eval()
            print("\tBatch", f"[{j}:{j+batch_size}]", ":", loss_fn(predict_proba(hm_model, X_batch), y_batch).item())
        hm_model.train()
            
    # Print epoch validation accuracy
    with torch.no_grad():
        hm_model.eval()
        print("Epoch", i+1, ":", "Dev accuracy:", evaluate(hm_model, X_val_tensor.to(device), y_val_tensor.to(device))*100, "%")
    hm_model.train()

with torch.no_grad():
    hm_model.eval()
    print("----------------")
    print("Test accuracy:", evaluate(hm_model, X_test_tensor.to(device), y_test_tensor.to(device))*100, "%")
    print("----------------")

Finished loading model, total used 259 iterations

Starting fine-tuning:

Initial dev accuracy: 33.559998869895935 %
	Batch [0:20000] : 8.698726654052734
	Batch [20000:40000] : 1.9178091287612915
	Batch [40000:60000] : 2.9061832427978516
	Batch [60000:80000] : 3.585233211517334
	Batch [80000:100000] : 3.0692758560180664
Epoch 1 : Dev accuracy: 33.149999380111694 %
	Batch [0:20000] : 1.868175745010376
	Batch [20000:40000] : 1.2286325693130493
	Batch [40000:60000] : 1.807142972946167
	Batch [60000:80000] : 2.308483600616455
	Batch [80000:100000] : 1.534917950630188
Epoch 2 : Dev accuracy: 80.35999536514282 %
	Batch [0:20000] : 0.8463166952133179
	Batch [20000:40000] : 0.9828970432281494
	Batch [40000:60000] : 1.2617058753967285
	Batch [60000:80000] : 1.3068169355392456
	Batch [80000:100000] : 1.0712077617645264
Epoch 3 : Dev accuracy: 37.209999561309814 %
	Batch [0:20000] : 0.70876145362854
	Batch [20000:40000] : 0.6016663908958435
	Batch [40000:60000] : 1.0703462362289429
	Batch [60000: